# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-24 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeAtor', models.CharField(max_length=200, verbose_name=b'Ator')),
                ('slug', models.SlugField(max_length=100, verbose_name=b'Identificador')),
                ('pais', models.CharField(max_length=100, verbose_name=b'Pa\xc3\xads')),
            ],
            options={
                'ordering': ['nomeAtor'],
                'verbose_name': 'Ator',
                'verbose_name_plural': 'Atores',
            },
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeFilme', models.CharField(max_length=200, verbose_name=b'Filme')),
                ('slug', models.SlugField(max_length=200, verbose_name=b'Identificador')),
                ('sinopse', models.TextField(blank=True, verbose_name=b'Sinopse')),
                ('resumo', models.CharField(max_length=150, verbose_name=b'Resumo')),
                ('atores', models.ManyToManyField(to='catalogo.Ator', verbose_name=b'Ator')),
            ],
            options={
                'ordering': ['nomeFilme'],
                'verbose_name': 'Filme',
                'verbose_name_plural': 'Filmes',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeGenero', models.CharField(max_length=100, verbose_name=b'G\xc3\xaanero')),
                ('slug', models.SlugField(max_length=100, verbose_name=b'Identificador')),
            ],
            options={
                'ordering': ['nomeGenero'],
                'verbose_name': 'G\xeanero',
                'verbose_name_plural': 'G\xeaneros',
            },
        ),
        migrations.AddField(
            model_name='filme',
            name='generos',
            field=models.ManyToManyField(to='catalogo.Genero', verbose_name=b'G\xc3\xaanero'),
        ),
    ]
