# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-25 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ator',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='atores', verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='filme',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='filmes', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='ator',
            name='nomeAtor',
            field=models.CharField(max_length=200, verbose_name='Ator'),
        ),
        migrations.AlterField(
            model_name='ator',
            name='pais',
            field=models.CharField(max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='ator',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='atores',
            field=models.ManyToManyField(to='catalogo.Ator', verbose_name='Ator'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='generos',
            field=models.ManyToManyField(to='catalogo.Genero', verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='nomeFilme',
            field=models.CharField(max_length=200, verbose_name='Filme'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='resumo',
            field=models.CharField(max_length=150, verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='sinopse',
            field=models.TextField(blank=True, verbose_name='Sinopse'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='slug',
            field=models.SlugField(max_length=200, verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nomeGenero',
            field=models.CharField(max_length=100, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Identificador'),
        ),
    ]
