# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-25 23:56
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20180225_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='popularidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ator',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=200, populate_from='nomeAtor', unique=True, verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=200, populate_from='nomeFilme', unique=True, verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from='nomeGenero', unique=True, verbose_name='Identificador'),
        ),
    ]
