# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-26 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20180225_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filme',
            options={'ordering': ['-popularidade'], 'verbose_name': 'Filme', 'verbose_name_plural': 'Filmes'},
        ),
        migrations.AlterField(
            model_name='filme',
            name='popularidade',
            field=models.IntegerField(default=0, verbose_name='Popularidade'),
        ),
    ]
