# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-27 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auto_20180225_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='trailer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Trailer'),
        ),
    ]
